# Generated by Django 5.0.6 on 2024-06-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
